(function(){var g=!0,i=!1,j;
function l(a){function b(){f||(f=g,d?c.e.ia=g:c.Z(a))}var c=this,d=i,f=i;c.za=a.useFlashFallback===i?i:!c.va;c.s=a.statBaseURL;c.H=a.guid||a.GUID;c.B=a.confID;c.j=a.viewableConversion;c.T=a.api&&!(a.api.bridge===a.api.fallbackAPI||a.api._BRIDGE===a.api.fallbackAPI);if(c.j){for(var e=a.viewableImpressionURL,h=[{param:"ft_creative",value:a.creativeID},{param:"ft_configuration",value:a.confID},{param:"ft_parent",value:window["ftTimestamp_"+a.pID]||""},{param:"ft_id",value:a.ftId||""},{param:"ft_custom",
value:window["ftCustom_"+a.pID]||""},{param:"ft_section",value:window["ftSection_"+a.pID]||""}],k=h.length;k--;)e=a.insertParam(e,h[k]);c.N="&"===e[e.length-1]?e.substring(0,e.length-1):e}c.width=parseInt(a.width,10);c.height=parseInt(a.height,10);c.b=242500<=c.width*c.height?0.6*a.viewableImpressionThreshold:a.viewableImpressionThreshold;c.v=0;c.Ea=i;c.M=a.viewableImpressionTime;c.L=i;c.K=i;c.p=a.customDefinition;c.k=0;c.ba=i;c.U=i;c.target=c.c?window.document.getElementById(a.divID):window.parent.document.getElementById(a.divID)||
window.frameElement;c.i=c.I=c.visibility.l;c.C=0;c.$=(new Date).getTime();c.aa=(new Date).getTime();c.n=0;c.o=0;c.t=0;c.xa=a.secure;c.a={visible:0,r:0,hidden:0,u:0};c.A=g;c.dispatchEvent=function(b,c){a.dispatchEvent(b,c)};if(a.fver&&a.minflashversion)this.D=!!a.fver();else{h=i;if(this.z)for(e=10;3<=e;e--)h=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+e),h=!!parseFloat(h.GetVariable("$version").match(/\b\d+\b/g).join("."));else"undefined"!=typeof navigator.plugins["Shockwave Flash"]&&(h=!!parseFloat(navigator.plugins["Shockwave Flash"].description.substring(15)));
this.D=h}c.c&&(window.$sf&&window.$sf.ext?c.q=c.wa:"undefined"!==typeof window.mozInnerScreenY?(c.X=c.la,c.G=c.ma):c.D&&!c.Q&&c.za?(c.F={},c.W=0,d=g,c.e={ia:i},c.g=[],c.V={id:"99",left:"-10000",top:"-1"},window.ftPagefoldFlashListener=function(b){b=b.split("-");c.qa(b[0],parseInt(b[1],10),a)},c.q=c.ra,c.ka()):(c.d(this.event.ha),!c.K&&c.j&&c.oa(),c.dispatchEvent("advisibility",i)));a.addEventListener("adonpage",b);a.addEventListener("backup",b)}
function m(a){var b="";this.s=a.statBaseURL;this.H=a.guid;this.B=a.confID;this.Q=/fox/i.test(navigator.appVersion);b=this.c?window.document.referrer:window.parent.document.location;b=escape(String(b).substr(0,200));this.d("314",b)}
function r(){this.B=this.H=this.s="";this.ta=window!=top;this.c=i;if(this.ta)try{window.parent.document.getElementsByTagName("head")[0].appendChild(window.parent.document.createElement("script"))}catch(a){this.c=g}this.Q=/fox/.test(navigator.userAgent);this.z=/MSIE/.test(navigator.userAgent);this.va=/Safari/.test(navigator.userAgent)&&!/Chrome/.test(navigator.userAgent)}l.prototype=new r;j=l.prototype;
j.event={ga:"301",fa:"302",P:"303",ea:"304",ca:"305",da:"306",O:"307",ha:"308",Da:"310",Ca:"311",Ba:"312"};j.visibility={f:2,m:1,l:0};j.R=[50,175,300,600,1200,3E3];
j.Z=function(a){var b=this;b.target=b.target||(b.c?document.getElementById(a.divID):window.parent.document.getElementById(a.divID)||window.frameElement);var c=this.q(),d=this.event.ea;1===c&&!b.p?d=this.event.ga:0<c&&(d=this.event.fa);this.d(d);this.i=this.I=this.Y(c);!a.api||"loading"!==a.api.getState()?this.S(a):a.api.addEventListener("ready",function(){b.S(a)})};
j.J=function(){var a=this,b=(new Date).getTime(),c=b-this.$-this.n,d=b-this.aa-this.o,f=this.q(),e=this.Y(f);a.A&&a.target.parentNode&&(this.dispatchEvent("advisibility",100*f),this.K?this.a.u+=d:1==f?this.a.visible+=d:0<f?this.a.r+=d:this.a.hidden+=d,this.p&&(e===this.visibility.f?this.k+=d:this.k<this.M&&(this.k=0),!this.ba&&this.k>=this.M&&(this.I===this.visibility.m?this.d(this.event.P):this.d(this.event.O),this.ba=g)),e>this.i&&this.ya(e),this.C<this.R.length&&this.h(c)>=this.R[this.C]&&(this.na(),
this.$=b,this.n=0,this.C++),a.j&&(!this.L&&this.N)&&(this.v=f>=this.b?this.v+d:0,this.v>=this.M&&(window.Ga=g,this.pa())),this.aa=b,this.o=0);a.target.parentNode&&((!a.T||a.T&&(a.j&&!a.L||!a.j&&!a.U))&&a.A)&&setTimeout(function(){a.J()},100)};
j.S=function(a){var b=this;b.t="yes"===a.pageVisible||b.c&&"no"!==a.pageVisible?0:(new Date).getTime();("yes"===a.pageVisible||b.c&&"no"!==a.pageVisible)&&b.J();a.addEventListener("visibilitychange",function(c){"yes"===c||b.c&&b.D&&"no"!==a.pageVisible?(b.n+=(new Date).getTime()-b.t,b.o+=(new Date).getTime()-b.t):(b.t=(new Date).getTime(),b.v=0);b.A="yes"===c||b.c&&"no"!==a.pageVisible;b.J()})};
j.na=function(){var a=[this.h(this.a.visible)];a.push(this.h(this.a.r));a.push(this.h(this.a.hidden));a.push(this.h(this.a.u));this.d("310",a.join("x"));this.a.visible=0;this.a.r=0;this.a.hidden=0;this.a.u=0;this.U=g};j.pa=function(){(new Image).src=this.N;this.L=g};j.oa=function(){(new Image).src=this.N.replace(/;202;pixel/,";270;pixel");this.K=g};
j.ya=function(a){var b;this.i===this.visibility.l?a===this.visibility.m?b=this.event.ca:a===this.visibility.f&&(b=this.event.da):this.i===this.visibility.m&&(a===this.visibility.f&&!this.p)&&(b=this.event.P,this.I===this.visibility.l&&(b=this.event.O));this.i=a;"undefined"!==typeof b&&this.d(b)};j.q=function(){var a=this.X(),b=this.G();return this.ja(a,b)};j.wa=function(){return window.$sf.ext.inViewPercentage()/100};
j.X=function(){var a=this.target.getBoundingClientRect(),b=this.G();return{x:a.left+b.scrollLeft,y:a.top+b.scrollTop}};
j.G=function(){var a={scrollLeft:0,scrollTop:0,height:0,width:0},b=window.parent;this.c||(b.innerWidth?(a.width=b.innerWidth,a.height=b.innerHeight,a.scrollLeft=b.pageXOffset,a.scrollTop=b.pageYOffset):b.document.documentElement&&b.document.documentElement.clientHeight?(a.width=b.document.documentElement.clientWidth,a.height=b.document.documentElement.clientHeight,a.scrollLeft=b.document.documentElement.scrollLeft,a.scrollTop=b.document.documentElement.scrollTop):b.document.body&&(a.width=b.document.body.clientWidth,
a.height=b.document.body.clientHeight,a.scrollLeft=b.document.body.scrollLeft,a.scrollTop=b.document.body.scrollTop));return a};j.ja=function(a,b){var c=b.scrollLeft,d=b.scrollLeft+b.width,f=b.scrollTop,e=b.scrollTop+b.height,h=a.x,k=a.x+this.width,n=a.y,p=a.y+this.height,t=(k-h)*(p-n),s=0,q;a:switch(g){case f>p:case c>k:case d<h:case e<n:q=g;break a;default:q=i}q||(c=Math.max(c,h),d=Math.min(d,k),f=Math.max(f,n),e=Math.min(e,p),s=(d-c)*(e-f));return Math.floor(100*(s/t))/100};
j.Y=function(a){var b=this.visibility.l;this.p&&a>=this.b?b=this.visibility.f:1===a?b=this.visibility.f:0<a&&(b=this.visibility.m);return b};j.la=function(){var a=this.target.getBoundingClientRect();return{x:window.mozInnerScreenX+a.left,y:window.mozInnerScreenY+a.top}};j.ma=function(){return{scrollLeft:window.screenX,scrollTop:window.screenY,height:window.outerHeight,width:window.outerWidth}};
j.ra=function(){function a(a,b){var f=0;return f=1>b?0:b<a?0.1:b<c?d:1}var b=0,c=0.5===this.b?9:12,d=this.b,f;for(f in this.F)b+=this.F[f]<0.8*this.W?1:0;return 0.5===d?a(5,b):0.5<d?a(8,b):0.39<d?a(6,b):a(4,b)};j.qa=function(a,b,c){var d=0;"99"===a?this.W=b:this.F[a]=b;this.e[a]=g;for(var f in this.e)this.e[f]||d++;0===d&&(this.Z(c),this.e.Fa=i)};
j.ka=function(){function a(a){return""+Math.round(a)}function b(a){var b="position: absolute; top: "+a.top+"px;",c=this.sa(a.id),b=b+(" width: "+this.w.width+"px;"),b=b+(" height: "+this.w.height+"px;"),b=b+(" left : "+a.left+"px; z-index: -1;");this.z?(a=d.replace("@STYLE@",b).replace("@FLASH@",c),this.target.insertAdjacentHTML("beforeend",a)):(a=document.createElement("div"),a.style.cssText=b,a.innerHTML=c,this.target.appendChild(a))}function c(){b.call(f,f.V);f.e[f.V.id]=i;for(var a=0,c=f.g.length;a<
c;a++)f.e[f.g[a].id]=i,b.call(f,f.g[a])}var d='<div style="@STYLE@">@FLASH@</div>',f=this,e=Math.sqrt(this.b);this.target.getBoundingClientRect();var h=[a(this.width*(1-e)),a(this.width*(1-this.b)),a(this.width*this.b),a(this.width*e)],e=[a(this.height*(1-e)),a(this.height*(1-this.b)),a(this.height*this.b),a(this.height*e)];this.g=[{id:"0",left:"0",top:e[0]},{id:"1",left:"0",top:e[3]},{id:"2",left:h[0],top:"0"},{id:"3",left:h[0],top:""+(this.height-1)},{id:"4",left:h[1],top:e[1]},{id:"5",left:h[1],
top:e[2]},{id:"6",left:h[2],top:e[1]},{id:"7",left:h[2],top:e[2]},{id:"8",left:h[3],top:"0"},{id:"9",left:h[3],top:""+(this.height-1)},{id:"10",left:""+(this.width-1),top:e[0]},{id:"11",left:""+(this.width-1),top:e[3]}];0.5===this.b&&(this.g=[{id:"0",left:"0",top:e[0]},{id:"1",left:"0",top:e[3]},{id:"2",left:h[0],top:"0"},{id:"3",left:h[0],top:+(this.height-1)},{id:"4",left:""+this.width/2,top:""+this.height/2},{id:"5",left:h[3],top:"0"},{id:"6",left:h[3],top:""+(this.height-1)},{id:"7",left:""+(this.width-
1),top:e[0]},{id:"8",left:""+(this.width-1),top:e[3]}]);document.body?c():this.ua(function(){document.body&&c()})};
j.sa=function(a){var b=this.w(),c=b.name+a,d;d="<OBJECT "+(this.z?'classid = "clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'data="'+b.path+'" type="application/x-shockwave-flash"');d=d+(' ID="'+c+'" name="'+c+'"')+(' width="'+b.width+'" height="'+b.height+'" style="float:left;">');d+='<PARAM NAME=movie VALUE="'+b.path+'"/>';d+='<PARAM NAME=FlashVars VALUE="identifier='+a+'"/>';d+='<PARAM NAME=quality VALUE="autohigh"/>';d+='<PARAM NAME=wmode VALUE="'+b.Aa+'"/>';d+='<PARAM NAME="allowScriptAccess" value="always"/>';
d+='<PARAM NAME="allowFullScreen" value="true"/>';return d+="</OBJECT>"};j.w=function(){return{path:(this.xa?"https":"http")+"://cdn.flashtalking.com/pageFold/pagefold.swf",name:"ftPF",width:1,height:2,Aa:"transparent"}};j.h=function(a){return Math.ceil(a/100)};m.prototype=new r;r.prototype.d=function(a,b){var c=[""+this.s+this.B];c.push(a);c.push("0");c.push(this.H);c.push(this.random());b&&c.push(b);this.s&&((new Image).src=c.join("-"))};
r.prototype.random=function(a){return Math.floor(Math.random()*(a||1E9))};r.prototype.ua=function(a){var b=document;"function"===typeof b.addEventListener?b.addEventListener("readystatechange",a,i):b.attachEvent("onreadystatechange",a)};window.ftPageFold_v3=function(a){a.breakingOut!==g&&(new l(a),a.campaignID&&27400>parseInt(a.campaignID,10)&&new m(a))};}());
